apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k4vw0b4ko-nodejs
  janus-idp.io/tekton: k4vw0b4ko-nodejs
  backstage.io/kubernetes-id: k4vw0b4ko-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k4vw0b4ko-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
